global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    prometheus_id: "hostmon-${HOSTNAME}"

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 'nodeexporter:9100'

  - job_name: 'cadvisor'
    static_configs:
    - targets:
      - 'cadvisor:8080'

  - job_name: 'blackbox_icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - d.yr32.net
        - oc.yr32.net
        - zerono.cloud
        - sjcl.me
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackboxexporter:9115

remote_write:
  - url: "http://nginx/api/v1/write"
